# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/node@16.13.2
    steps:
      - checkout
      - run: yarn install
      - run: yarn test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  first_workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      # - node/test:
      #     # This is the node version to use for the `cimg/node` tag
      #     # Relevant tags can be found on the CircleCI Developer Hub
      #     # https://circleci.com/developer/images/image/cimg/node
      #     version: '16.13.2'
      #     # If you are using yarn, change the line below from "npm" to "yarn"
      #     pkg-manager: yarn
